# Generated by Django 3.2.7 on 2021-09-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('aboutyou', models.TextField(max_length=1000)),
                ('careerobj', models.TextField(max_length=500)),
                ('education', models.TextField(max_length=1000)),
                ('j3sd', models.DateField()),
                ('j3ed', models.DateField()),
                ('postiondet3', models.TextField(max_length=500)),
                ('j2sd', models.DateField()),
                ('j2ed', models.DateField()),
                ('postiondet2', models.TextField(max_length=500)),
                ('j1sd', models.DateField()),
                ('j1ed', models.DateField()),
                ('postiondet1', models.TextField(max_length=500)),
                ('references', models.TextField()),
            ],
        ),
    ]
