# Generated by Django 3.2.7 on 2021-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210925_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createresume',
            old_name='postiondet1',
            new_name='positiondet1',
        ),
        migrations.RenameField(
            model_name='createresume',
            old_name='postiondet2',
            new_name='positiondet2',
        ),
        migrations.RenameField(
            model_name='createresume',
            old_name='postiondet3',
            new_name='positiondet3',
        ),
        migrations.AlterField(
            model_name='createresume',
            name='references',
            field=models.TextField(max_length=600),
        ),
    ]
